### ISSUE TITLE
NVIC_SM_1: Expected and unexpected interrupt check

### ISSUE THREAD

**Issue by rbiasini** [commaai/panda#334]

**Comment by robbederks** [comment]
The guidelines for the implementation of the method are the following:
* The list of the implemented interrupt for the MCU are well documented, reporting also theexpected frequency of each request when possible (for example the interrupts related toADC conversion completion, therefore coming on a deterministic way).
* Individual counters are maintained for each interrupt request served, in order to detect in agiven time frame the cases of a) no interrupt at all b) too many interrupt requests (“babblingidiot” interrupt source). The control of the time frame duration must be regulated accordingto the individual interrupt expected frequency.
* Interrupt vectors related to unused interrupt source point to a default handler that reports,in case of triggering, a faulty condition (unexpected interrupt).
* In case an interrupt service routine is shared between different sources, a plausibility checkon the caller identity is implemented.
* Interrupt requests related to non-safety-related peripherals are handled with the samemethod here described, despite their originator safety classification
