### ISSUE TITLE
ISO26262: failure in set_safety_mode should result in setting NOOUTPUT. Failure is setting NOOUTPUT should result in hang

### ISSUE THREAD

**Issue by geohot** [commaai/panda#386]
On master, panda fw: v1.6.3-EON-8a044b34-DEBUG

root@localhost:~/one/panda/board$ python
Python 3.7.3 (default, Apr 24 2019, 11:21:56) 
[Clang 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec7462 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import
KeyboardInterrupt
>>> import panda
>>> panda.Panda().set_safety_mode(0x1337)
opening device 540031000651363038363036 0xddcc
connected

Panda is hung, LED is no longer blinking.

**Comment by jyoung8607** [comment]
That's intentional, and should have put something in the debug console buffer. See this commit:

https://github.com/commaai/panda/commit/0e72c18378b04d22ea502027e9d5cc0d0e3a25fe

It was part of some cleanup of the init and safety setting code. It carried forward the old init-time behavior of stopping if the safety mode could not be set, and made it applicable for all failures not just init-time.

https://github.com/commaai/panda/blob/ff86db65538a2ac8bace47a1790fb7d8fd933287/board/main.c#L772

If you don't want to halt/spin on setting an invalid safety mode, then don't. But, it should probably be modified to set SAFETY_NOOUTPUT instead.

**Comment by jyoung8607** [comment]
Following up to myself, because I knew 0x1337 looked familiar.... the Panda safety list was aligned with cereal a while back, and SAFETY_ALLOUTPUT was renumbered from 0x1337 to 17. I didn't realize you intended to set a valid working safety mode when I replied earlier, I thought you were fuzzing, but I think the substance of my reply applies anyway.

**Comment by geohot** [comment]
Crashing is never okay. No output is fine.

**Comment by rbiasini** [comment]
yeah, I can make it default to noOutput is safety mode setting fails and then ok to hang if that one fails too.

**Comment by rbiasini** [comment]
https://github.com/commaai/panda/commit/a54b86c4baa8ee935c659436abde6ba94715c439
