### ISSUE TITLE
Can't change safety mode to ALLOUTPUT

### ISSUE THREAD

**Issue by omertal323** [commaai/panda#569]
p.change_safety_mode(17) is not changing safety mode (according to p.health()). every other safety mode works. This issue blocks me from sending arbitrary CAN messages.

**Comment by jyoung8607** [comment]
Be sure you have flashed Panda with debug firmware, otherwise certain community-supported safety modes and the all-output safety mode aren't enabled. If testing with something other than openpilot, you'll also need the EON option unset, or the lack of boardd keepalives will set Panda back to no output a few seconds later. Try building from source and flashing on Ubuntu, where I believe both of those will happen by default.

**Comment by omertal323** [comment]
Thanks for the help

I can't flash anything, the LED is flashing green and device stop
responding till power reset...

**Comment by omertal323** [comment]
I seemd to have solved the problem! there was a problem with the udev rule
in the readme, the syntax is not corrent to my ubuntu machine. Anyway, now
i managed to flashed a debug version and successfully change into ALLOUTPUT
safety mode.

If I may ask another question, is there a way to enable this mode on WIFI
too? this is really important to me since this is the reason I purchased
the device at all :)

Thanks,
Omer
